### ISSUE TITLE
Failed to parse headers (url=https://access-alexa-na.amazon.com:443/v1/avs/speechrecognizer/recognize): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: 

### ISSUE THREAD

**Issue by q64ceo** [alexa/avs-device-sdk#1610]
Reading Audible and Kindle books do not work. Here is the log:

[31/01/2020 15:07:06] Alexa got response
[31/01/2020 15:10:49] Found Alexa keyword
[31/01/2020 15:10:52] Finished 3.5s
[31/01/2020 15:10:52] Starting new HTTPS connection (1): access-alexa-na.amazon.com
[31/01/2020 15:10:54] https://access-alexa-na.amazon.com:443 "POST /v1/avs/speechrecognizer/recognize HTTP/1.1" 200 None
[31/01/2020 15:10:54] Failed to parse headers (url=https://access-alexa-na.amazon.com:443/v1/avs/speechrecognizer/recognize): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 399, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/lib/python3/dist-packages/urllib3/util/response.py", line 66, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''

I am using pop_os 18.04 on a Dell G5 15 5590 laptop

**Comment by q64ceo** [comment]
Whoops, my fault for not provisioning my device.
