### ISSUE TITLE
AuthDelegate Error for installing AVS SDK for arm target

### ISSUE THREAD

**Issue by dhananjayj29** [alexa/avs-device-sdk#287]
Hi 
I am getting the following errors while running Sample App on My ARM target.
2017-10-31 12:01:31.470 [  2] I AlertsCapabilityAgent:executeScheduleNextAlertForRendering::no work to do.
2017-10-31 12:01:31.470 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0xc9c70,policy=BLOCKING
2017-10-31 12:01:31.470 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=ClearQueue,handler=0xca1d8,policy=NON_BLOCKING
2017-10-31 12:01:31.470 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Stop,handler=0xca1d8,policy=NON_BLOCKING
2017-10-31 12:01:31.470 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Play,handler=0xca1d8,policy=NON_BLOCKING
2017-10-31 12:01:31.471 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0xc8340,policy=NON_BLOCKING
2017-10-31 12:01:31.471 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=StopCapture,handler=0xc8340,policy=NON_BLOCKING
2017-10-31 12:01:31.471 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=DeleteAlert,handler=0xcadd0,policy=NON_BLOCKING
2017-10-31 12:01:31.471 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=SetAlert,handler=0xcadd0,policy=NON_BLOCKING
2017-10-31 12:01:31.471 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=SetEndpoint,handler=0xdd708,policy=NON_BLOCKING
2017-10-31 12:01:31.471 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=ResetUserInactivity,handler=0xc8124,policy=NON_BLOCKING
2017-10-31 12:01:33.218 [  3] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=60,error=Error
2017-10-31 12:01:33.218 [  3] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2017-10-31 12:01:34.623 [  3] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=60,error=Error
2017-10-31 12:01:34.623 [  3] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2017-10-31 12:01:36.423 [  3] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=60,error=Error
2017-10-31 12:01:36.423 [  3] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2017-10-31 12:01:39.418 [  3] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=60,error=Error
2017-10-31 12:01:39.418 [  3] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
2017-10-31 12:01:45.604 [  3] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=60,error=Error
2017-10-31 12:01:45.604 [  3] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
Failed to authorize SDK client!
2017-10-31 12:01:51.482 [  1] I DirectiveSequencer:doShutdown
2017-10-31 12:01:51.483 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=System,name=SetEndpoint,handler=0xdd708,policy=NON_BLOCKING
2017-10-31 12:01:51.483 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=Alerts,name=DeleteAlert,handler=0xcadd0,policy=NON_BLOCKING
2017-10-31 12:01:51.483 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=Alerts,name=SetAlert,handler=0xcadd0,policy=NON_BLOCKING
2017-10-31 12:01:51.483 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0xc8340,policy=NON_BLOCKING
2017-10-31 12:01:51.483 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=SpeechRecognizer,name=StopCapture,handler=0xc8340,policy=NON_BLOCKING
2017-10-31 12:01:51.483 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=AudioPlayer,name=ClearQueue,handler=0xca1d8,policy=NON_BLOCKING
2017-10-31 12:01:51.483 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=AudioPlayer,name=Stop,handler=0xca1d8,policy=NON_BLOCKING
2017-10-31 12:01:51.483 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=AudioPlayer,name=Play,handler=0xca1d8,policy=NON_BLOCKING
2017-10-31 12:01:51.483 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=System,name=ResetUserInactivity,handler=0xc8124,policy=NON_BLOCKING
2017-10-31 12:01:51.484 [  1] I DirectiveRouter:removeDirectiveHandlers:action=removed,namespace=SpeechSynthesizer,name=Speak,handler=0xc9c70,policy=BLOCKING
2017-10-31 12:01:51.484 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0xdd708
2017-10-31 12:01:51.484 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0xcadd0
2017-10-31 12:01:51.484 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0xc8340
2017-10-31 12:01:51.484 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0xca1d8
2017-10-31 12:01:51.484 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0xc8124
2017-10-31 12:01:51.484 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0xc9c70

(SampleApp:3433): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
2017-10-31 12:01:51.489 [  4] E MediaPlayer:doStopFailed:reason=gstElementGetStateFailed

(SampleApp:3433): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:3433): GLib-CRITICAL **: g_source_remove: assertion 'tag > 0' failed

(SampleApp:3433): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
2017-10-31 12:01:51.491 [  4] E MediaPlayer:doStopFailed:reason=gstElementGetStateFailed

(SampleApp:3433): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:3433): GLib-CRITICAL **: Source ID 583304 was not found when attempting to remove it
Failed to initialize SampleApplication
Failed to create to SampleApplication!

Note:
It looks like related to LWA 
1. I don't have the browser on my target system , so I have followed the refresh token generation process on my ubuntu desktop and copied the same in target system
2. Also previously I was getting below errors:
E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=60,error=Peer certificate cannot be authenticated with given CA certificates
E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
As I have built curl without-ca-bundle ,without-ca-path and disabling the authetication support.
After this  Peer certificate cannot be authenticated with given CA certificates error went off.

But still getting the below errors:
HttpPost:doPostFailed:reason=curl_easy_performFailed,result=60,error=Error
2017-10-31 12:01:36.423 [  3] E AuthDelegate:handleLwaResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.

I am not able to make out whether these errors are related to LWA or SSL ca certification authentication.
I have built curl with nghttp2 and openssl-1.1.0f versions.
Please let me know the way to fix this.

**Comment by frozenberg** [comment]
Hi @dhananjayj29, could you provide me your AlexaClientSDKConfig.json file? You can block out any sensitive information with asterisks.

Also could you provide the logs from the start of the application?

**Comment by dhananjayj29** [comment]
[AlexaClientSDKConfig.txt](https://github.com/alexa/avs-device-sdk/files/1436530/AlexaClientSDKConfig.txt)
[Target_logs.txt](https://github.com/alexa/avs-device-sdk/files/1436534/Target_logs.txt)

Thanks for the reply...
Attached the required files.

**Comment by frozenberg** [comment]
Hi again,

You might need to fill out the config.json file a bit more. Check step 3.2 [here](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide). Namely, the lack of a CertifiedSender field could cause issues.

**Comment by dhananjayj29** [comment]
Hi 
I have added the CertifiedSender filed on json file , But still issue persists.
Tested with both manually  created the db file  on target and in another step let the SDK create this file.(SDK did not created this db file)
And in both the above test cycles seen the same error SSL certification issue.

**Comment by dhananjayj29** [comment]
Hi
I was able to fix above error by getting ca cert bundle and setting path .
However I am getting further issues on AVS Http2 connection side.
I have attached full log .
Also i fixed ALSA playback and capture related errors by providing the correct ALSA hw device to asoundrc file.

but errors mentioned in the attached log files seems to be either HTTP2 connection issues or gstreamer issues .
Any help to figure this out would be appreciated.
[Target_log511.txt](https://github.com/alexa/avs-device-sdk/files/1446201/Target_log511.txt)

**Comment by frozenberg** [comment]
I'm not sure which logs you are referring to. Can you send me the logs again and also tell me what steps you took to reproduce it? Are the errors happening just as you start the app up or are you giving a command to listen to music or something?

**Comment by dhananjayj29** [comment]
Hi Frozenberg,
I was able to fix below issues:
1. No server response for HTTP2 query 
    - Some Firewall and network setting changed fixed this issue.
2. Playback erorr.
   - Gstreamer configuration redone for MP3 plugin and able to fix this issue

But after that below issues are seen 
1. whatever Audio is being played is playing with very low volume and am not able to increase it to appropriate level. I have tried increasing the volume through alexa command but no luck.
Also other audio playback which happened on my system through a Third party player has appropriate volume levels . so my doubt is source streams had a very low amplitude and due to which playback streams are not played at proper volume ,
Need your help in fixing this.

2. Sometimes after asking question to Alexa , SDK is crashed with below logs.(This issue is seen sometoimes)
Alexa crash issue with slow network:

###########################
#       Thinking...       #
###########################
2017-11-08 10:08:49.042 [  d] I InProcessAttachmentReader:readFailed:reason=SDS is closed
< HTTP/2 200 
< access-control-allow-origin: *
< x-amzn-requestid: 0292b7fffe85fd8a-00001242-00048d9d-ca6242c41ce4ad07-6e2febb6-5
2017-11-08 10:08:50.572 [  d] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 0292b7fffe85fd8a-00001242-00048d9d-ca6242c41ce4ad07-6e2febb6-5
< content-type: multipart/related;boundary=98ae684d-e8c6-4e46-a59c-eb267093e6c4;start=metadata.1510549900386;type="application/json"
< 
2017-11-08 10:08:50.997 [  6] I DirectiveSequencer:onDirective:directive={"namespace\:"Speaker"\,name\:"SetMute"\,messageId\:"b32b4de4-84bb-4135-9f2d-fb506ce867a4"\,dialogRequestId\:"85f63508-56f3-4a46-b5}
2017-11-08 10:08:50.998 [  6] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechSynthesizer"\,name\:"Speak"\,messageId\:"1097ec71-03ff-43a1-81bf-e7bc3b1dd070"\,dialogRequestId\:"85f63508-56f3}
2017-11-08 10:08:50.998 [  b] W DirectiveRouter:preHandleDirectiveFailed:messageId=b32b4de4-84bb-4135-9f2d-fb506ce867a4,reason=noHandlerRegistered
2017-11-08 10:08:50.998 [  b] I DirectiveSequencer:sendingExceptionEncountered:messageId=b32b4de4-84bb-4135-9f2d-fb506ce867a4
2017-11-08 10:08:50.999 [  b] 0 EventBuilder:buildJsonEventString:messageId=446dd4d3-4f86-4047-9bbc-5bf243d9bf3c,namespace=System,name=ExceptionEncountered
2017-11-08 10:08:50.999 [  b] I DirectiveRouter:preHandleDirective:messageId=1097ec71-03ff-43a1-81bf-e7bc3b1dd070,action=calling
2017-11-08 10:08:50.999 [  b] 0 CapabilityAgent:addingMessageIdToMap:messageId=1097ec71-03ff-43a1-81bf-e7bc3b1dd070
2017-11-08 10:08:50.999 [  b] 9 SpeechSynthesizer:preHandleDirective:messageId=1097ec71-03ff-43a1-81bf-e7bc3b1dd070
2017-11-08 10:08:51.000 [  c] I DirectiveRouter:handleDirective:messageId=1097ec71-03ff-43a1-81bf-e7bc3b1dd070,action=calling
2017-11-08 10:08:51.000 [  9] 0 SpeechSynthesizer:executePreHandle:messageId=1097ec71-03ff-43a1-81bf-e7bc3b1dd070
2017-11-08 10:08:51.000 [  c] 9 SpeechSynthesizer:handleDirective:messageId=1097ec71-03ff-43a1-81bf-e7bc3b1dd070
2017-11-08 10:08:51.004 [  9] 0 SpeechSynthesizer:executeHandle:messageId=1097ec71-03ff-43a1-81bf-e7bc3b1dd070
2017-11-08 10:08:51.005 [  f] 0 SpeechSynthesizer:onFocusChanged:newFocus=FOREGROUND
2017-11-08 10:08:51.005 [  a] 0 AudioInputProcessor:executeOnFocusChanged:newFocus=NONE
2017-11-08 10:08:51.005 [  a] 0 AudioInputProcessor:executeOnFocusChanged:reason=Lost focus
2017-11-08 10:08:51.005 [  a] 0 AudioInputProcessor:setState:from=BUSY,to=IDLE
2017-11-08 10:08:51.005 [  9] 0 SpeechSynthesizer:executeStateChange:newState=PLAYING
2017-11-08 10:08:51.006 [  9] 9 SpeechSynthesizer:startPlaying
2017-11-08 10:08:51.006 [  9] 9 MediaPlayer:setSourceCalled:sourceType=AttachmentReader
2017-11-08 10:08:51.006 [  2] 0 MediaPlayer:handleSetSourceCalled
2017-11-08 10:08:51.007 [  2] 9 MediaPlayer:tearDownPipeline
* Found bundle for host avs-alexa-eu.amazon.com: 0x27af78 [can multiplex]
* Conn: 0 (0x238610) Receive pipe weight: (-1/0), penalized: (nil)
* Multiplexed connection found!
* Found connection 0, with requests in the pipe (2)
* Re-using existing connection! (#0) with host avs-alexa-eu.amazon.com
* Using Stream ID: 7 (easy handle 0x2b5d48)
> POST /v20160207/events HTTP/2
Host: avs-alexa-eu.amazon.com
Accept: */*
Authorization: Bearer Atza|IwEBIMfcSGBabhdb8nwbQPjv0jdpoROIZj6iQP0_s_Bjk5g2TuCy-GWTqZ7cvpEPt1ZD5l6J-lsF1i-7rrCd9q8bHezjHmBVOykYKp5YRuQdNzdYOfYVA0wB01ET-Lu3L9nYjytuc8-8xUE5SVsrUMgU9NTyz5yBcKpsP2185B4CaynkSA
Content-Length: 637
Content-Type: multipart/form-data; boundary=------------------------1fffc3d2a29bf6d4

2017-11-08 10:08:51.069 [  9] 9 MediaPlayer:playCalled
2017-11-08 10:08:51.069 [  2] 0 MediaPlayer:handlePlayCalled
2017-11-08 10:08:51.069 [  2] 0 MediaPlayer:doStopSuccess:reason=alreadyStopped
2017-11-08 10:08:51.070 [  2] 9 MediaPlayer:doStopSuccess
2017-11-08 10:08:51.070 [  2] 0 MediaPlayer:handlePlay:supportsBuffering=0
2017-11-08 10:08:51.083 [  2] 0 MediaPlayer:handlePlay:stateReturn=ASYNC
terminate called after throwing an instance of 'std::future_error'
  what():  Promise already satisfied
Aborted (core dumped)


Please provide some pointers.

**Comment by scotthea-amazon** [comment]
Hello dhananjayj29,

Sorry for the long delayed response.  Do you know what version of the SDK you were using when you observed the 

> what(): Promise already satisfied

 message?  I am asking because an issue like this was addressed in the 1.1 release.

Regarding the low volume issue, are you still experiencing it?  If so, can you tell us more about your audio configuration?

Thank you,
-SWH

**Comment by dhananjayj29** [comment]
Hi,
I was able to fix the volume issue , it was ALSA conf issue in my system.
But the AVS stack getting crash is still there.

This issue was reported on 1.0.x version and recently I moved to 1.2.1 version of SDK.
I am still getting the same issue. Also only after 2-3 queries/questions to stack it is crashing.

Latest logs are as below:

###########################
#       Listening...       #
############################

2018-01-08 23:12:51.661 [  8] 9 MediaPlayer:getSpeakerSettingsCalled
2018-01-08 23:12:51.662 [  2] 9 MediaPlayer:handleGetSpeakerSettingsCalled
method return time=1515453171.663897 sender=:1.50 -> destination=:1.52 serial=13 reply_serial=2
   int32 1
2018-01-08 23:12:51.665 [  8] 9 SpeakerManager:validateSpeakerSettingsConsistencyResult:consistent=true
2018-01-08 23:12:51.666 [  8] 9 SpeakerManager:validateSpeakerSettings:volume=100,mute=false
2018-01-08 23:12:51.666 [  8] 0 ContextManager:updateStateLocked:action=updatedState,state={"volume"\:100\,"muted"\:false},namespace=Speaker,name=VolumeState
2018-01-08 23:12:51.666 [  6] 0 ContextManager:buildContextSuccessful:context={"context"\:[{"header"\:{"namespace"\:"Speaker"\,"name"\:"VolumeState"}\,"payload"\:{"volume"\:100\,"muted"\:false}}\,{"header}
2018-01-08 23:12:51.667 [  9] 0 AudioInputProcessor:executeOnContextAvailable:jsonContext={"context"\:[{"header"\:{"namespace"\:"Speaker"\,"name"\:"VolumeState"}\,"payload"\:{"volume"\:100\,"muted"\:false}
2018-01-08 23:12:51.667 [  9] 1 FocusManager:acquireChannel:channelName=Dialog,activityId=SpeechRecognizer.Recognize
2018-01-08 23:12:51.667 [  9] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=bb138449-49cc-4115-8774-a99e9636e993,newValue=b60f6d41-a18a-4d19-a92b-2a82ab310186
2018-01-08 23:12:51.668 [  9] 0 DirectiveProcessor:scrubDialogRequestIdLocked:dialogRequestId=bb138449-49cc-4115-8774-a99e9636e993
2018-01-08 23:12:51.668 [  9] 0 EventBuilder:buildJsonEventString:messageId=50861716-ea48-4394-bafb-f957ded89547,namespace=SpeechRecognizer,name=Recognize
2018-01-08 23:12:51.668 [  9] 0 AudioInputProcessor:executeOnFocusChanged:newFocus=FOREGROUND
2018-01-08 23:12:51.668 [  9] 9 HTTP2Transport:enqueueRequest:jsonContent={"context"\:[{"header"\:{"namespace"\:"Speaker"\,"name"\:"VolumeState"}\,"payload"\:{"volume"\:100\,"muted"\:false}}\,{"header"\:{}
2018-01-08 23:12:52.008 [ 11] 0 HTTP2Transport:processNextOutgoingMessage:jsonContent={"context"\:[{"header"\:{"namespace"\:"Speaker"\,"name"\:"VolumeState"}\,"payload"\:{"volume"\:100\,"muted"\:false}}\,}
2018-01-08 23:12:52.009 [ 11] 0 HTTP2StreamPool:getStream:streamId=11,numAcquiredStreams=2
2018-01-08 23:12:52.009 [ 11] 9 HTTP2Transport:insertActiveStream:handle=0xb3db5de8
2018-01-08 23:12:52.009 [ 11] I HTTP2Stream:libcurl:streamId=11,text=Found bundle for host avs-alexa-eu.amazon.com\: 0xb3d022a8 [can multiplex]
2018-01-08 23:12:52.010 [ 11] I HTTP2Stream:libcurl:streamId=11,text=Conn\: 0 (0xb3d01968) Receive pipe weight\: (-1/0)\, penalized\: (nil)
2018-01-08 23:12:52.010 [ 11] I HTTP2Stream:libcurl:streamId=11,text=Multiplexed connection found!
2018-01-08 23:12:52.010 [ 11] I HTTP2Stream:libcurl:streamId=11,text=Found connection 0\, with requests in the pipe (1)
2018-01-08 23:12:52.010 [ 11] I HTTP2Stream:libcurl:streamId=11,text=Re-using existing connection! (#0) with host avs-alexa-eu.amazon.com
2018-01-08 23:12:52.010 [ 11] I HTTP2Stream:libcurl:streamId=11,text=Using Stream ID\: 7 (easy handle 0xb3db5de8)
root@info3-low:~# 2018-01-08 23:12:55.245 [  c] 0 MessageInterpreter:receive:messageId=d2672482-ea89-4d7e-a0dc-61549025e589:No dialogRequestId attached to message.
2018-01-08 23:12:55.245 [  c] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"StopCapture"\,messageId\:"d2672482-ea89-4d7e-a0dc-61549025e589"\,dialogRequestId\:""}
2018-01-08 23:12:55.245 [  d] I DirectiveRouter:preHandleDirective:messageId=d2672482-ea89-4d7e-a0dc-61549025e589,action=calling
2018-01-08 23:12:55.245 [  d] 0 CapabilityAgent:addingMessageIdToMap:messageId=d2672482-ea89-4d7e-a0dc-61549025e589
2018-01-08 23:12:55.246 [  e] I DirectiveRouter:handleDirective:messageId=d2672482-ea89-4d7e-a0dc-61549025e589,action=calling
2018-01-08 23:12:55.246 [  9] 0 AudioInputProcessor:stopCapture:stopImmediately=true
2018-01-08 23:12:55.246 [  9] 0 AudioInputProcessor:setState:from=RECOGNIZING,to=BUSY
2018-01-08 23:12:55.246 [  9] 0 DirectiveProcessor:onHandlingCompeted:messageId=d2672482-ea89-4d7e-a0dc-61549025e589,directiveBeingPreHandled=(nullptr)
2018-01-08 23:12:55.246 [ 12] 0 DialogUXStateAggregator:setState:from=LISTENING,to=THINKING
2018-01-08 23:12:55.246 [  9] 0 CapabilityAgent:removingMessageIdFromMap:messageId=d2672482-ea89-4d7e-a0dc-61549025e589
###########################
#       Thinking...       #
###########################

2018-01-08 23:12:55.273 [ 11] I InProcessAttachmentReader:readFailed:reason=SDS is closed
2018-01-08 23:12:55.719 [ 11] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 0a6d4efffe8d0e30-00004d37-00017a71-de38fc9a59d24fcf-3e80229a-7
2018-01-08 23:12:55.942 [  c] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechSynthesizer"\,name\:"Speak"\,messageId\:"0e8dbd6c-63c0-4e25-803c-f4630137c28d"\,dialogRequestId\:"b60f6d41-a18a}
2018-01-08 23:12:55.942 [  d] I DirectiveRouter:preHandleDirective:messageId=0e8dbd6c-63c0-4e25-803c-f4630137c28d,action=calling
2018-01-08 23:12:55.942 [  d] 0 CapabilityAgent:addingMessageIdToMap:messageId=0e8dbd6c-63c0-4e25-803c-f4630137c28d
2018-01-08 23:12:55.943 [  d] 9 SpeechSynthesizer:preHandleDirective:messageId=0e8dbd6c-63c0-4e25-803c-f4630137c28d
2018-01-08 23:12:55.943 [  7] 0 SpeechSynthesizer:executePreHandle:messageId=0e8dbd6c-63c0-4e25-803c-f4630137c28d
2018-01-08 23:12:55.944 [  e] I DirectiveRouter:handleDirective:messageId=0e8dbd6c-63c0-4e25-803c-f4630137c28d,action=calling
2018-01-08 23:12:55.944 [  e] 9 SpeechSynthesizer:handleDirective:messageId=0e8dbd6c-63c0-4e25-803c-f4630137c28d
2018-01-08 23:12:55.948 [  7] 0 SpeechSynthesizer:executeHandle:messageId=0e8dbd6c-63c0-4e25-803c-f4630137c28d
2018-01-08 23:12:55.948 [  7] 1 FocusManager:acquireChannel:channelName=Dialog,activityId=SpeechSynthesizer.Speak
2018-01-08 23:12:55.948 [ 13] 0 SpeechSynthesizer:onFocusChanged:newFocus=FOREGROUND
2018-01-08 23:12:55.948 [  9] 0 AudioInputProcessor:executeOnFocusChanged:newFocus=NONE
2018-01-08 23:12:55.949 [  9] 0 AudioInputProcessor:executeOnFocusChanged:reason=Lost focus
2018-01-08 23:12:55.949 [  9] 0 AudioInputProcessor:setState:from=BUSY,to=IDLE
2018-01-08 23:12:55.949 [  7] 0 SpeechSynthesizer:executeStateChange:newState=PLAYING
2018-01-08 23:12:55.950 [ 12] 0 DialogUXStateAggregator:setState:from=THINKING,to=IDLE
2018-01-08 23:12:55.950 [  7] 9 SpeechSynthesizer:startPlaying
2018-01-08 23:12:55.950 [  7] 9 MediaPlayer:setSourceCalled:sourceType=AttachmentReader
########################################
#       Alexa is currently idle!       #
########################################

2018-01-08 23:12:55.951 [  2] 0 MediaPlayer:handleSetSourceCalled
2018-01-08 23:12:55.951 [  2] 9 MediaPlayer:tearDownTransientPipelineElements
2018-01-08 23:12:56.030 [  7] 9 MediaPlayer:playCalled
2018-01-08 23:12:56.031 [  2] 0 MediaPlayer:handlePlayCalled:idPassed=1,currentId=1
Please let me know the hint/root cause , I am kind of stuck and can not proceed without this fix.

Also stack strace for this issue is changed:

#5  0xb6c2d73c in __cxxabiv1::__cxa_throw (obj=0xb3e0d928, tinfo=<optimized out>, dest=<optimized out>)
    at libstdc++-v3/libsupc++/eh_throw.cc:84
#6  0xb6c80824 in std::__throw_future_error (__i=__i@entry=2) at functexcept.cc:109
#7  0xb6f46ef0 in _M_set_result (__ignore_failure=false, __res=..., this=0xb3401900) at future:360
#8  std::promise<bool>::set_value(bool&&) (this=this@entry=0xb6553218 <g_idle_dispatch>, 
    __r=__r@entry=<unknown type in /usr/lib/libMediaPlayer.so, CU 0x46162, DIE 0x89a5d>)
    at  future:994
#9  0xb6f3ebe4 in alexaClientSDK::mediaPlayer::MediaPlayer::handlePlay (this=0x9a248, id=<optimized out>, promise=0xac9fe86c)
    at /avs-device-sdk/MediaPlayer/src/MediaPlayer.cpp:1026
#10 0xb6f3efdc in operator() (__closure=<optimized out>) at avs-device-sdk/MediaPlayer/src/MediaPlayer.cpp:228
#11 std::_Function_handler<int(), alexaClientSDK::mediaPlayer::MediaPlayer::play(alexaClientSDK::avsCommon::utils::mediaPlayer::MediaPlayerInterface::SourceId)::__lambda9>::_M_invoke(const std::_Any_data &) (__functor=...) at functional:2056
#12 0xb65568dc in g_main_dispatch (context=0x110e08) at gmain.c:3154
