### ISSUE TITLE
startauth.sh error

### ISSUE THREAD

**Issue by YanLiudchyk** [alexa/avs-device-sdk#567]
When i launch startauth.sh, it throws this error:

Traceback (most recent call last):
  File "AuthServer.py", line 82, in <module>
    configData = commentjson.load(configFile)
  File "C:\msys64\mingw64\lib\python2.7\site-packages/commentjson/commentjson.py", line 94, in load
    raise JSONLibraryException(e.message)
commentjson.commentjson.JSONLibraryException: JSON Library Exception

Exception thrown by JSON library (json): [4;37mJSON Library Exception

Exception thrown by JSON library (json): [4;37mInvalid control character at: line 18 column 80 (char 570)[0m

    Traceback (most recent call last):
      File "C:\msys64\mingw64\lib\python2.7\site-packages/commentjson/commentjson.py", line 57, in loads
        return json.loads('\n'.join(lines), **kwargs)
      File "C:\msys64\mingw64\lib\python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "C:\msys64\mingw64\lib\python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\msys64\mingw64\lib\python2.7/json/decoder.py", line 380, in raw_decode
        obj, end = self.scan_once(s, idx)
    ValueError: Invalid control character at: line 18 column 80 (char 570)
    [0m

    Traceback (most recent call last):
      File "C:\msys64\mingw64\lib\python2.7\site-packages/commentjson/commentjson.py", line 92, in load
        return loads(fp.read(), **kwargs)
      File "C:\msys64\mingw64\lib\python2.7\site-packages/commentjson/commentjson.py", line 59, in loads
        raise JSONLibraryException(e.message)
    JSONLibraryException: JSON Library Exception

    Exception thrown by JSON library (json): [4;37mInvalid control character at: line 18 column 80 (char 570)[0m

        Traceback (most recent call last):
          File "C:\msys64\mingw64\lib\python2.7\site-packages/commentjson/commentjson.py", line 57, in loads
            return json.loads('\n'.join(lines), **kwargs)
          File "C:\msys64\mingw64\lib\python2.7/json/__init__.py", line 339, in loads
            return _default_decoder.decode(s)
          File "C:\msys64\mingw64\lib\python2.7/json/decoder.py", line 364, in decode
            obj, end = self.raw_decode(s, idx=_w(s, 0).end())
          File "C:\msys64\mingw64\lib\python2.7/json/decoder.py", line 380, in raw_decode
            obj, end = self.scan_once(s, idx)
        ValueError: Invalid control character at: line 18 column 80 (char 570)

**Comment by ENT8R** [comment]
According to your log there is an issue in "line 18 column 80". So very probably you have a malformed JSON with all your credentials. Maybe you can paste your content of the config-JSON at this website: https://jsonlint.com/ and find (and fix) the issue this way...

**Comment by celinval** [comment]
Thanks for you help @ENT8R!

Hi @YanLiudchyk, as @ENT8R mentioned, it looks like your JSON is malformed. Please inspect line 18 column 80.

BTW, please don't copy your credentials into any website, since this is private information.
