### ISSUE TITLE
SampleApp was killed with core-dump while long-run test.

### ISSUE THREAD

**Issue by tifler** [alexa/avs-device-sdk#886]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

The SampleApp was killed with core dump after running for 3days. It listened to my speaker saying "Alexa, Good morning!" once a minute repeatedly.

## What is the expected behavior?

SampleApp should work infinitely without any problem.

## What behavior are you observing?

I was executing long-run test which sends "Alexa, Good morning" to AVS periodically.

## Provide the steps to reproduce the issue, if applicable:

1. My PC's speaker says "Alexa, Good morning!" once a minute.
2. And then my speaker speaks "Good morning, blah blah~".
3. Go to 1st step.

### What version of the AVS Device SDK are you using?
      <1.8.1>
1. Here are some of last logs.
```
########################################
#       Alexa is currently idle!       #
########################################

2018-08-05 04:35:01.358 [  e] 5 TemplateRuntime:onDialogUXStateChanged:state=IDLE
2018-08-05 04:35:01.360 [ 13] I LEDManager:setLED:led=AI,color=CYAN,mode=OFF
2018-08-05 04:35:01.360 [ 1c] 1 FocusManager:releaseChannel:channelName=Dialog
2018-08-05 04:35:01.361 [ 23] 0 SpeechSynthesizer:onFocusChanged:newFocus=NONE
2018-08-05 04:35:01.361 [ 23] 5 AudioActivityTracker:notifyOfActivityUpdates
2018-08-05 04:35:01.362 [ 1d] 5 AudioActivityTracker:executeNotifyOfActivityUpdates
2018-08-05 04:35:01.712 [7096] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 0e115afffed119d2-000073a2-001f90a2-b2b227b11a07adbe-cfb89502-175
2018-08-05 04:35:01.713 [7096] 0 HTTP2Transport:cleanupFinishedStream:streamId=83791,result=204
2018-08-05 04:35:01.713 [7096] 0 HTTP2StreamPool:releaseStream:streamId=83791,numAcquiredStreams=1
2018-08-05 04:35:01.714 [7096] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2018-08-05 04:35:03.809 [ 2a] I BatteryManager:updateBatteryInfo:l=97,v=4142000,chg=Full,h=Good,cl=High,online=1
[268557.753068] AMP_PDN_EN OFF!!!
0
2018-08-05 04:35:06.155 [ 11] E PortAudioMicrophoneWrapper:=====> Trigger started.
2018-08-05 04:35:06.176 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=0,numSamples=1024
2018-08-05 04:35:06.240 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=1024,numSamples=1024
2018-08-05 04:35:06.304 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=2048,numSamples=1024
2018-08-05 04:35:06.368 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=3072,numSamples=1024
2018-08-05 04:35:06.432 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=4096,numSamples=1024
2018-08-05 04:35:06.496 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=5120,numSamples=1024
2018-08-05 04:35:06.560 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=6144,numSamples=1024
2018-08-05 04:35:06.624 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=7168,numSamples=1024
2018-08-05 04:35:06.688 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=8192,numSamples=1024
2018-08-05 04:35:06.752 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=9216,numSamples=1024
2018-08-05 04:35:06.816 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=10240,numSamples=1024
2018-08-05 04:35:06.880 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=11264,numSamples=1024
2018-08-05 04:35:06.902 [ 1a] 0 AudioInputProcessor:setState:from=IDLE,to=RECOGNIZING
2018-08-05 04:35:06.902 [  e] 0 DialogUXStateAggregator:setState:from=IDLE,to=LISTENING
2018-08-05 04:35:06.902 [ 19] 5 AudioActivityTracker:provideState
2018-08-05 04:35:06.903 [ 1d]  5 AudioActivityTracker:executeProvideState
2018-08-05 04:35:06.903 [ 22] I SoundIndicator:Start Listening.############################
#       Listening...       #
############################


2018-08-05 04:35:06.903 [ 1d] 9 ContextManager:updateStateLocked:action=updatedState,namespace=AudioActivityTracker,name=ActivityState
2018-08-05 04:35:06.903 [ 22] I SoundIndicator:START_LISTENING
2018-08-05 04:35:06.903 [ 22] 9 MediaPlayer:setSourceCalled:sourceType=istream
2018-08-05 04:35:06.904 [  2] 0 MediaPlayer:handleSetSourceCCaalllleedd
2018-08-05 04:35:06.904 [  2] 9 MediaPlayer:tearDownTransientPipelineElements
2018-08-05 04:35:06.904 [ 13] I LEDManager:setLED:led=AI,color=CYAN,mode=ON
2018-08-05 04:35:06.904 [  2] E MediaPlayer:saveOffsetBeforeTeardown - gst_element_query_position failed
2018-08-05 04:35:06.903 [ 19] 5 NotificationsCapabilityAgent:provideState:stateRequestToken=14549
2018-08-05 04:35:06.905 [  2] 9 BaseStreamSource:initNoAudioFormat
2018-08-05 04:35:06.905 [ 19] 5 VisualActivityTracker:provideState
2018-08-05 04:35:06.906 [ 1f] 0 ExternalMediaPlayer:executeProvideState:sendToken=true,stateRequestToken=14549
2018-08-05 04:35:06.906 [ 1f] 9 ContextManager:updateStateLocked:action=updatedState,namespace=ExternalMediaPlayer,name=ExternalMediaPlayerState
2018-08-05 04:35:06.906 [ 1f] 0 ExternalMediaPlayer:executeProvideState:sendToken=true,stateRequestToken=14549
2018-08-05 04:35:06.907 [ 1f] 9 ContextManager:updateStateLocked:action=updatedState,namespace=Alexa.PlaybackStateReporter,name=playbackState
2018-08-05 04:35:06.907 [ 1e] 5 VisualActivityTracker:executeProvideState
2018-08-05 04:35:06.907 [ 1e] 9 ContextManager:updateStateLocked:action=updatedState,namespace=VisualActivityTracker,name=ActivityState
2018-08-05 04:35:06.906 [  d] 5 NotificationsCapabilityAgent:executeProvideState:sendToken=true,stateRequestToken=14549
2018-08-05 04:35:06.908 [ 22] 9 MediaPlayer:playCalled
2018-08-05 04:35:06.909 [  d] 9 ContextManager:updateStateLocked:action=updatedState,namespace=Notifications,name=IndicatorState
2018-08-05 04:35:06.909 [  2] 0 MediaPlayer:handlePlayCalled:idPassed=43141,currentId=43141
2018-08-05 04:35:06.910 [ 19] 9 ContextManager:buildContextIgnored:namespace=VisualActivityTracker,name=ActivityState
2018-08-05 04:35:06.910 [ 19] 5 ContextManager:buildContextSuccessful
2018-08-05 04:35:06.903 [  e] 5 TemplateRuntime:onDialogUXStateChanged:state=LISTENING
2018-08-05 04:35:06.911 [ 1a] 0 AudioInputProcessor:executeOnContextAvailable
2018-08-05 04:35:06.911 [ 1a] 1 FocusManager:acquireChannel:channelName=Dialog,interface=SpeechRecognizer
2018-08-05 04:35:06.911 [ 1a] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=34087dfe-2712-4beb-bf18-dbc78d995a3c,newValue=b38bb76f-3e52-48fc-a229-5b06bb7d130f
2018-08-05 04:35:06.911 [ 1a] 0 DirectiveProcessor:scrubDialogRequestIdLocked:dialogRequestId=34087dfe-2712-4beb-bf18-dbc78d995a3c
2018-08-05 04:35:06.912 [ 23] 9 AudioInputProcessor:onFocusChanged:newFocus=FOREGROUND
2018-08-05 04:35:06.912 [ 23] 5 AudioActivityTracker:notifyOfActivityUpdates
2018-08-05 04:35:06.912 [ 1a] 0 EventBuilder:buildJsonEventString:messageId=74445cfd-14d5-42c6-8aa0-988900387f11,namespace=SpeechRecognizer,name=Recognize
2018-08-05 04:35:06.913 [ 1d] 5 AudioActivityTracker:executeNotifyOfActivityUpdates
2018-08-05 04:35:06.913 [ 1a] 0 AudioInputProcessor:executeOnFocusChanged:newFocus=FOREGROUND
2018-08-05 04:35:06.913 [ 1a] 9 HTTP2Transport:enqueueRequest
2018-08-05 04:35:06.927 [  2] 0 MediaPlayer:handlePlay:startingState=PLAYING,stateReturn=ASYNC
2018-08-05 04:35:06.928 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=audio_sink-actual-sink-alsa
2018-08-05 04:35:06.928 [7120] 9 BaseStreamSource:onNeedDataCalled:size=4096
2018-08-05 04:35:06.928 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=audio_sink
2018-08-05 04:35:06.928 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=capsfilter6
2018-08-05 04:35:06.928 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=caps
2018-08-05 04:35:06.928 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=resample
2018-08-05 04:35:06.928 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=volume
2018-08-05 04:35:06.929 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=converter
2018-08-05 04:35:06.929 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=typefind
2018-08-05 04:35:06.929 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=decoder
2018-08-05 04:35:06.929 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=src
2018-08-05 04:35:06.929 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=audio-pipeline
2018-08-05 04:35:06.929 [  2] 9 MediaPlayer:State Change:oldState=NULL,newState=READY,pendingState=PLAYING
2018-08-05 04:35:06.929 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=capsfilter6
2018-08-05 04:35:06.929 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=caps
2018-08-05 04:35:06.929 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=resample
2018-08-05 04:35:06.930 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=volume
2018-08-05 04:35:06.930 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=converter
2018-08-05 04:35:06.930 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=typefind
2018-08-05 04:35:06.930 [  2] 9 MediaPlayer:messageReceived:type=stream-status,source=src
2018-08-05 04:35:06.930 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=src
2018-08-05 04:35:06.930 [  2] 9 MediaPlayer:messageReceived:type=stream-status,source=src
2018-08-05 04:35:06.930 [  2] 9 BaseStreamSource:handleNeedDataCalled
2018-08-05 04:35:06.930 [  2] 9 BaseStreamSource:installOnReadDataHandler:action=newSourceId,sourceId=143889
2018-08-05 04:35:06.931 [  2] 9 IStreamSource:read:size=4096,pos=4096,eof=false
2018-08-05 04:35:06.931 [  2] 9 IStreamSource:read:size=4096,pos=8192,eof=false
2018-08-05 04:35:06.931 [  2] 9 IStreamSource:read:size=4096,pos=12288,eof=false
2018-08-05 04:35:06.931 [  2] 9 IStreamSource:read:size=4096,pos=16384,eof=false
2018-08-05 04:35:06.931 [  2] 9 IStreamSource:read:size=4096,pos=20480,eof=false
2018-08-05 04:35:06.931 [  2] 9 IStreamSource:read:size=4096,pos=24576,eof=false
2018-08-05 04:35:06.932 [  2] 9 IStreamSource:read:size=4096,pos=28672,eof=false
2018-08-05 04:35:06.932 [  2] 9 IStreamSource:read:size=4096,pos=32768,eof=false
2018-08-05 04:35:06.944 [ 21] E PortAudioMicrophoneWrapper:Trigger:Pos=12288,numSamples=1024
2018-08-05 04:35:06.957 [7120] 9 MediaPlayer:onPadAddedCalled
2018-08-05 04:35:06.974 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=wavparse28751
2018-08-05 04:35:06.967 [7096] 0 HTTP2Transport:processNextOutgoingMessage
2018-08-05 04:35:06.974 [  2] 9 MediaPlayer:messageReceived:type=state-changed,source=wavparse28751
2018-08-05 04:35:06.975 [7096] 0 HTTP2StreamPool:getStream:streamId=83793,numAcquiredStreams=2
2018-08-05 04:35:06.975 [  2] 9 IStreamSource:read:size=4096,pos=36864,eof=false
2018-08-05 04:35:06.975 [  2] 9 MediaPlayer:handlePadAddedSignalCalled
2018-08-05 04:35:06.975 [7096] 9 HTTP2Transport:insertActiveStream:handle=0x4cab08
2018-08-05 04:35:06.977 [7096] E InProcessAttachmentReader:readFailed:reason=bytes requested smaller than SDS word size
2018-08-05 04:35:06.977 [7096] E InProcessAttachmentReader:readFailed:reason=bytes requested smaller than SDS word size
2018-08-05 04:35:06.977 [7096] E InProcessAttachmentReader:readFailed:reason=bytes requested smaller than SDS word size
bluetoothd[1545]: Endpoint unregistered: sender=:1.3 path=/com/amazon/alexa/sdk/sinkendpoint
Segmentation fault (core dumped)
```
2. Here is the backtrace of the core

```
(gdb) bt
#0  0xb65b6c2c in memcpy () from staging/lib/libc.so.6
#1  0xb6c32968 in alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::Reader::read (this=<optimized out>, buf=0x4cb2e0, nWords=<optimized out>, nWords@entry=8192, timeout=...,
    timeout@entry=...)
    at /home2/tifler/work/prj-odysseus/axela-uroad/uroad/output/build/avs-device-sdk-v1.8.1/AVSCommon/Utils/include/AVSCommon/Utils/SDS/Reader.h:321
#2  0xb6c31410 in alexaClientSDK::avsCommon::avs::attachment::InProcessAttachmentReader::read (this=0xb45a19a0,
    buf=buf@entry=0x4cb2e0, numBytes=numBytes@entry=16384, readStatus=0x906fe6f4, readStatus@entry=0x906fe6ec,
    timeoutMs=timeoutMs@entry=...)
    at /home2/tifler/work/prj-odysseus/axela-uroad/uroad/output/build/avs-device-sdk-v1.8.1/AVSCommon/AVS/src/Attachment/InProcessAttachmentReader.cpp:112
#3  0xb5f420b0 in alexaClientSDK::acl::HTTP2Stream::readCallback (data=0x4cb2e0 "", size=1, nmemb=16384,
    userData=<optimized out>)
    at /home2/tifler/work/prj-odysseus/axela-uroad/uroad/output/build/avs-device-sdk-v1.8.1/ACL/src/Transport/HTTP2Stream.cpp:409
#4  0xb5f01a54 in readback_part () from staging/usr/lib/libcurl.so.4
#5  0xb5f01bc4 in mime_subparts_read () from staging/usr/lib/libcurl.so.4
#6  0xb5f01a54 in readback_part () from staging/usr/lib/libcurl.so.4
#7  0xb5ee19c0 in Curl_fillreadbuffer () from staging/usr/lib/libcurl.so.4
#8  0xb5ee2868 in Curl_readwrite () from staging/usr/lib/libcurl.so.4
#9  0xb5ee9fd8 in multi_runsingle () from staging/usr/lib/libcurl.so.4
#10 0xb5eea428 in curl_multi_perform () from staging/usr/lib/libcurl.so.4
#11 0xb6c4c874 in alexaClientSDK::avsCommon::utils::libcurlUtils::CurlMultiHandleWrapper::perform (this=<optimized out>,
    runningHandles=runningHandles@entry=0x906fec60)
    at /home2/tifler/work/prj-odysseus/axela-uroad/uroad/output/build/avs-device-sdk-v1.8.1/AVSCommon/Utils/src/LibcurlUtils/CurlMultiHandleWrapper.cpp:89
#12 0xb5f47a54 in alexaClientSDK::acl::HTTP2Transport::networkLoop (this=0x8fd2e818)
    at /home2/tifler/work/prj-odysseus/axela-uroad/uroad/output/build/avs-device-sdk-v1.8.1/ACL/src/Transport/HTTP2Transport.cpp:337
#13 0xb67b6a70 in execute_native_thread_routine () from staging/usr/lib/libstdc++.so.6
#14 0xb6db9f2c in start_thread () from staging/lib/libpthread.so.0
#15 0xb6607fe8 in ?? () from staging/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

```

3. I'm wondering there is a wrap-around bug, because the segmentation fault occurred almost in 3 days after launching the long-run test.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [O] Other - tell us more: **We made a custom speaker using avs-device-sdk's SampleApp.**

### Tell us about your OS (Type & version):
- [O] Linux - Linux kernel 4.4 + buildroot
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mavamazon** [comment]
Thank you for your report, it does seem like a bug! We will investigate it and let you know the outcome.

**Comment by kclchan** [comment]
Hi @tifler, sorry for not getting back to you sooner.  Is this issue still open?  Could you try again with v1.10 of SDK?  Thanks!

**Comment by tifler** [comment]
Hi @kclchan. Okay, I'll upgrade the version of the SDK and check it again, but it'll take some time. Thanks!

**Comment by kjkh** [comment]
Hi @tifler,

Any updates on this? Are you still seeing failures?

**Comment by mvelegon-amzn** [comment]
Hi @tifler Please let us know if you are still seeing the issue on the latest version of the SDK.

**Comment by kclchan** [comment]
I am closing this issue due to inactivity. Please feel free to re-open it if it has been closed in error.
